M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Fri 12 Aug 2022 09:34:58 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-12T21:34:58-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.1469
%
G90
G05
T1
X4.6572Y-3.1961
X5.1493Y-2.822
X6.0548Y-3.9047
X6.1729Y-2.822
T0
M30
