M48
; DRILL file {KiCad 6.0.0+dfsg1-2} date Tue 08 Feb 2022 01:12:32 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-08T13:12:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0+dfsg1-2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0299
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0866
%
G90
G05
T1
X6.3252Y-5.0197
X6.3252Y-5.3228
X6.5252Y-5.0197
X6.5252Y-5.3228
T2
X4.8689Y-4.3457
T3
X5.3404Y-3.7234
T4
X5.5512Y-4.4685
X6.063Y-5.2756
X6.9488Y-3.7598
T0
M30
