M48
; DRILL file {KiCad 8.0.8+dfsg-1} date 2025-03-16T16:56:27-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-16T16:56:27-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.1220
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.1469
%
G90
G05
T1
X5.5745Y-4.0307
T2
X5.8816Y-3.9874
T3
X4.6572Y-3.1961
X5.1493Y-2.822
X6.0548Y-3.9047
X6.1729Y-2.822
M30
